version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm run build
  test:
    machine: true
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
